rvm:
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - jruby-19mode

before_script:
  - psql -c 'create database gryphon_sitemap_test;' -U postgres
  - cp spec/dummy/config/database.yml.example spec/dummy/config/database.yml

notifications:
  email: 
    - explorer@flame.org
