development:
  adapter: postgresql
  encoding: unicode
  database: gryphon_sitemap_development
  pool: 5
  username: explorer
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: gryphon_sitemap_test
  pool: 5
  username: explorer
  password:
